- name: Update Authentik server
  hosts: all
  become: yes
  tasks:
    - name: Pull latest Authentik images
      ansible.builtin.shell: docker-compose pull
      args:
        chdir: /home/authentik/docker/authentik/install

    - name: Recreate Authentik containers with the latest images
      ansible.builtin.shell: docker-compose up -d
      args:
        chdir: /home/authentik/docker/authentik/install
